# Generated by Django 5.0.6 on 2024-05-15 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='category',
            new_name='cat_id',
        ),
    ]
