# Generated by Django 5.0.6 on 2024-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_rename_category_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
